# Generated by Django 5.2 on 2025-04-18 05:27

import vault.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=vault.models.user_directory_path)),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('size', models.BigIntegerField()),
                ('file_hash', models.CharField(max_length=64, unique=True)),
            ],
        ),
    ]
