# Generated by Django 5.2 on 2025-04-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_file_is_duplicate_file_original_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_hash',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='file',
            name='filename',
            field=models.CharField(max_length=255),
        ),
    ]
