# Generated by Django 5.2 on 2025-04-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_alter_file_file_hash_alter_file_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='filename',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
